"""add member rank check constraint

Revision ID: 20222eea16fd
Revises: 0fafcf93de97
Create Date: 2026-09-04 20:23:58.642946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20222eea16fd'
down_revision: Union[str, Sequence[str], None] = '0fafcf93de97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members") as batch_op:
        batch_op.create_check_constraint(
            "ck_members_rank_valid",
            "rank IN ('MEMBER', 'R4', 'R5')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members") as batch_op:
        batch_op.drop_constraint(
            "ck_members_rank_valid",
            type_="check",
        )
    # ### end Alembic commands ###
