"""add member rank

Revision ID: b802f8d8a50f
Revises: 48019be6d3b8
Create Date: 2026-09-04 09:58:43.752700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b802f8d8a50f'
down_revision: Union[str, Sequence[str], None] = '48019be6d3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('rank', sa.String(length=20), server_default='MEMBER', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'rank')
    # ### end Alembic commands ###
